=== kkzzhizhou/scoop-apps/bucket/schema.json
{
    "$id": "http://scoop.sh/draft/schema#",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "additionalProperties": false,
    "definitions": {
        "architecture": {
            "additionalProperties": false,
            "properties": {
                "bin": {
                    "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
                },
                "checkver": {
                    "$ref": "#/definitions/checkver"
                },
                "extract_dir": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "hash": {
                    "$ref": "#/definitions/hash"
                },
                "installer": {
                    "$ref": "#/definitions/installer"
                },
                "msi": {
                    "$ref": "#/definitions/stringOrArrayOfStrings",
                    "description": "Deprecated"
                },
                "post_install": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "pre_install": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "shortcuts": {
                    "$ref": "#/definitions/shortcutsArray"
                },
                "uninstaller": {
                    "$ref": "#/definitions/uninstaller"
                },
                "url": {
                    "$ref": "#/definitions/uriOrArrayOfUris"
                }
            },
            "type": "object"
        },
        "arrayOfArrayOfStrings": {
            "items": {
                "items": {
                    "type": "string"
                },
                "minItems": 1,
                "type": "array"
            },
            "minItems": 1,
            "type": "array"
        },
        "autoupdate": {
            "additionalProperties": false,
            "properties": {
                "architecture": {
                    "additionalProperties": false,
                    "properties": {
                        "32bit": {
                            "additionalProperties": false,
                            "properties": {
                                "extract_dir": {
                                    "type": "string"
                                },
                                "hash": {
                                    "$ref": "#/definitions/hashExtraction"
                                },
                                "url": {
                                    "format": "uri",
                                    "type": "string"
                                }
                            },
                            "type": "object"
                        },
                        "64bit": {
                            "additionalProperties": false,
                            "properties": {
                                "extract_dir": {
                                    "type": "string"
                                },
                                "hash": {
                                    "$ref": "#/definitions/hashExtraction"
                                },
                                "url": {
                                    "format": "uri",
                                    "type": "string"
                                }
                            },
                            "type": "object"
                        }
                    },
                    "type": "object"
                },
                "extract_dir": {
                    "type": "string"
                },
                "hash": {
                    "$ref": "#/definitions/hashExtraction"
                },
                "note": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "url": {
                    "format": "uri",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "checkver": {
            "anyOf": [
                {
                    "format": "regex",
                    "type": "string"
                },
                {
                    "additionalProperties": false,
                    "properties": {
                        "github": {
                            "format": "uri",
                            "type": "string"
                        },
                        "jp": {
                            "pattern": "^\\$\\..*$",
                            "type": "string"
                        },
                        "re": {
                            "format": "regex",
                            "type": "string"
                        },
                        "replace": {
                            "description": "Allows rearrange the regexp matches",
                            "type": "string"
                        },
                        "reverse": {
                            "description": "Reverse the order of regex matches",
                            "type": "boolean"
                        },
                        "url": {
                            "format": "uri",
                            "type": "string"
                        }
                    },
                    "type": "object"
                }
            ]
        },
        "hash": {
            "anyOf": [
                {
                    "$ref": "#/definitions/hashPattern"
                },
                {
                    "items": {
                        "$ref": "#/definitions/hashPattern"
                    },
                    "minItems": 1,
                    "type": "array",
                    "uniqueItems": true
                }
            ]
        },
        "hashExtraction": {
            "additionalProperties": false,
            "properties": {
                "find": {
                    "format": "regex",
                    "type": "string"
                },
                "jp": {
                    "pattern": "^\\$\\..*$",
                    "type": "string"
                },
                "mode": {
                    "enum": [
                        "download",
                        "extract",
                        "json",
                        "rdf"
                    ]
                },
                "type": {
                    "description": "Deprecated, hash type is determined automatically",
                    "enum": [
                        "md5",
                        "sha1",
                        "sha256",
                        "sha512"
                    ]
                },
                "url": {
                    "anyOf": [
                        {
                            "format": "uri",
                            "type": "string"
                        },
                        {
                            "pattern": "^(\\$url|\\$baseurl).[\\w\\d]+$",
                            "type": "string"
                        },
                        {
                            "pattern": "^.*(\\$url|\\$baseurl).*$",
                            "type": "string"
                        }
                    ]
                }
            },
            "type": "object"
        },
        "hashPattern": {
            "pattern": "^([a-fA-F0-9]{64}|(sha1|sha256|sha512|md5):([a-fA-F0-9]{32}|[a-fA-F0-9]{40}|[a-fA-F0-9]{64}|[a-fA-F0-9]{128}))$",
            "type": "string"
        },
        "installer": {
            "additionalProperties": false,
            "properties": {
                "_comment": {
                    "description": "Undocumented: only used in scoop-extras/oraclejdk* and scoop-extras/appengine-go",
                    "type": "string"
                },
                "args": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "file": {
                    "type": "string"
                },
                "keep": {
                    "type": "boolean"
                },
                "script": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                }
            },
            "type": "object"
        },
        "shortcutsArray": {
            "items": {
                "items": {
                    "type": "string"
                },
                "maxItems": 4,
                "minItems": 2,
                "type": "array"
            },
            "minItems": 1,
            "type": "array"
        },
        "stringOrArrayOfStrings": {
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "items": {
                        "type": "string"
                    },
                    "minItems": 1,
                    "type": "array"
                }
            ]
        },
        "stringOrArrayOfStringsOrAnArrayOfArrayOfStrings": {
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "items": {
                        "$ref": "#/definitions/stringOrArrayOfStrings"
                    },
                    "minItems": 1,
                    "type": "array"
                }
            ]
        },
        "uninstaller": {
            "oneOf": [
                {
                    "required": [
                        "file"
                    ]
                },
                {
                    "required": [
                        "script"
                    ]
                }
            ],
            "properties": {
                "args": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "file": {
                    "type": "string"
                },
                "script": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                }
            },
            "type": "object"
        },
        "uriOrArrayOfUris": {
            "anyOf": [
                {
                    "format": "uri",
                    "not": {
                        "pattern": "(\\$)"
                    },
                    "type": "string"
                },
                {
                    "items": {
                        "format": "uri",
                        "not": {
                            "pattern": "(\\$)"
                        },
                        "type": "string"
                    },
                    "minItems": 1,
                    "type": "array",
                    "uniqueItems": true
                }
            ]
        }
    },
    "properties": {
        "##": {
            "$ref": "#/definitions/stringOrArrayOfStrings",
            "description": "A comment."
        },
        "_comment": {
            "$ref": "#/definitions/stringOrArrayOfStrings",
            "description": "Undocumented: only found in scoop/git* and 6 manifests in scoop-extras"
        },
        "architecture": {
            "additionalProperties": false,
            "properties": {
                "32bit": {
                    "$ref": "#/definitions/architecture"
                },
                "64bit": {
                    "$ref": "#/definitions/architecture"
                }
            },
            "type": "object"
        },
        "autoupdate": {
            "$ref": "#/definitions/autoupdate"
        },
        "bin": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
        },
        "checkver": {
            "$ref": "#/definitions/checkver"
        },
        "cookie": {
            "description": "Undocumented: only found in scoop-extras/oraclejdk*",
            "type": "object"
        },
        "depends": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "description": {
            "type": "string"
        },
        "env_add_path": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "env_set": {
            "type": "object"
        },
        "extract_dir": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "extract_to": {
            "$ref": "#/definitions/stringOrArrayOfStrings",
            "description": "Undocumented: only found in scoop/ruby*"
        },
        "hash": {
            "$ref": "#/definitions/hash"
        },
        "homepage": {
            "format": "uri",
            "type": "string"
        },
        "innosetup": {
            "description": "Undocumented: only found in 6 manifests in scoop",
            "type": "boolean"
        },
        "installer": {
            "$ref": "#/definitions/installer"
        },
        "license": {
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "additionalProperties": false,
                    "properties": {
                        "identifier": {
                            "type": "string"
                        },
                        "url": {
                            "format": "uri",
                            "type": "string"
                        }
                    },
                    "required": [
                        "identifier"
                    ],
                    "type": "object"
                }
            ]
        },
        "msi": {
            "$ref": "#/definitions/stringOrArrayOfStrings",
            "description": "Deprecated"
        },
        "notes": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "persist": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
        },
        "post_install": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "pre_install": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "psmodule": {
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "shortcuts": {
            "$ref": "#/definitions/shortcutsArray"
        },
        "suggest": {
            "additionalProperties": false,
            "patternProperties": {
                "^(.*)$": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                }
            },
            "type": "object"
        },
        "uninstaller": {
            "$ref": "#/definitions/uninstaller"
        },
        "url": {
            "$ref": "#/definitions/uriOrArrayOfUris"
        },
        "version": {
            "pattern": "^[\\w\\.\\-_]+$",
            "type": "string"
        }
    },
    "required": [
        "version"
    ],
    "title": "scoop app manifest schema",
    "type": "object"
}

=== kkzzhizhou/scoop-apps/bucket/good-mitm.json
{
    "version": "0.2.4",
    "description": "利用MITM技术实现请求和返回的重写、重定向、阻断等操作",
    "homepage": "https://github.com/zu1k/good-mitm",
    "license": "MIT",
    "architecture": {
        "64bit": {
            "url": "https://github.com/zu1k/good-mitm/releases/download/0.2.4/good-mitm-x86_64-pc-windows-gnu-0.2.4.zip",
            "hash": "81d0fac27f07270174da935af1f5a37cdc272a2e83f51d6de0f1c7fbad36c127"
        }
    },
    "extract_dir": "bin",
    "pre_install": "Get-ChildItem \"$dir\" 'good-mitm-*.exe' | Select-Object -First 1 | Rename-Item -NewName 'good-mitm.exe'",
    "bin": "good-mitm.exe",
    "checkver": "github",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/zu1k/good-mitm/releases/download/$version/good-mitm-x86_64-pc-windows-gnu-$version.zip"
            }
        }
    }
}

=== kkzzhizhou/scoop-apps/bucket/sirikali-aoks.json
{
    "version": "1.8.5",
    "description": "A Qt/C++ GUI front end to sshfs, ecryptfs-simple, cryfs, gocryptfs, securefs, fscrypt and encfs.",
    "homepage": "https://mhogomchungu.github.io/sirikali/",
    "license": "GPL-2.0-or-later",
    "architecture": {
        "64bit": {
            "url": "https://github.com/mhogomchungu/sirikali/releases/download/1.8.5/SiriKaliQt6-1.8.5.zip",
            "hash": "18682c37204ef8e77006093019112ce84bb82b270775b57ddb6d3ac9cef2ef47"
        }
    },
    "##": "see installer options here - https://jrsoftware.org/ishelp/index.php?topic=setupcmdline",
    "bin": "sirikali.exe",
    "depends": "nonportable/sshfs-np",
    "checkver": {
        "github": "https://github.com/mhogomchungu/sirikali"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/mhogomchungu/sirikali/releases/download/$version/SiriKaliQt6-$version.zip"
            }
        }
    }
}

=== kkzzhizhou/scoop-apps/bucket/avogadro2.json
{
    "version": "1.102.0",
    "homepage": "https://two.avogadro.cc/index.html",
    "description": "The official continuation of the advanced molecule editor and visualizer designed for use in computational chemistry, molecular modeling, bioinformatics, materials science, and related areas.",
    "license": "BSD-3-Clause",
    "architecture": {
        "64bit": {
            "url": "https://github.com/OpenChemistry/avogadrolibs/releases/download/1.102.0/Avogadro2-1.102.0-win64.exe#/dl.7z",
            "hash": "fdaa95eee317f75caf39fbd7b4a2de081be47abfe41f9541fb86f37f160f6950"
        }
    },
    "pre_install": "Remove-Item \"$dir\" -Include 'Uninstall.exe', '$PLUGINSDIR' -Recurse",
    "bin": "bin\\avogadro2.exe",
    "shortcuts": [
        [
            "bin\\avogadro2.exe",
            "Avogadro 2"
        ]
    ],
    "checkver": {
        "github": "https://github.com/OpenChemistry/avogadrolibs"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/OpenChemistry/avogadrolibs/releases/download/$version/Avogadro2-$version-win64.exe#/dl.7z"
            }
        }
    }
}

=== kkzzhizhou/scoop-apps/bucket/khinsider-downloader.json
{
    "version": "2.8.0.0",
    "homepage": "https://github.com/weespin/KhinsiderDownloader",
    "description": "A simple Bulk Khinsider downloader with a GUI.",
    "license": "MIT",
    "url": "https://github.com/weespin/KhinsiderDownloader/releases/download/2.8.0.0/Release.zip",
    "hash": "5111772a574553665413aec33b1dabba5b1b83e1a1e53b73218d190cacf45fde",
    "shortcuts": [
        [
            "KhinsiderDownloader.exe",
            "KhinsiderDownloader"
        ]
    ],
    "persist": "Downloads",
    "checkver": "github",
    "autoupdate": {
        "url": "https://github.com/weespin/KhinsiderDownloader/releases/download/$version/Release.zip"
    }
}

=== kkzzhizhou/scoop-apps/bucket/FileLocatorPro.json
{
    "version": "9.2.3435.1",
    "description": "FileLocator Pro 是一款高性能、专业的文件搜索工具。",
    "homepage": "https://www.mythicsoft.com/filelocatorpro/",
    "license": {
        "identifier": "Shareware",
        "url": "https://www.mythicsoft.com/filelocatorpro/buy/"
    },
    "url": [
        "https://download.mythicsoft.com/flp/3435/filelocator_inx64_3435.exe#/filelocator_inx64.exe",
        "https://github.com/maboloshi/scoop-private/releases/download/v1.0/FileLocatorPro-CrackPatch-v9.2.3435.1.zip"
    ],
    "hash": [
        "d2f21b187a2abd0304d5a7f16ddf88d02a035b120fe85ef24571f450350a02c2",
        "a639cc8fb8071d7c89f29300fb9cf13680c34815cd5c2697639f8ab311903dad"
    ],
    "extract_to": [
        "",
        "patch"
    ],
    "innosetup": true,
    "pre_install": [
        "ensure \"$persist_dir\\config\" | Out-Null",
        "@('config_v9.xml', 'history.xml', 'index.xml') | ForEach-Object { if (!(Test-Path \"$persist_dir\\config\\$_\")) { New-Item -Path \"$persist_dir\\config\\$_\" -ItemType File | Out-Null } }"
    ],
    "post_install": [
        "Write-Host `r`n'Applying crack patch...' -Foreground DarkCyan",
        "Copy-Item -Path \"$dir\\patch\\*\" -Destination \"$dir\" -Force -Recurse",
        "Remove-Item -Path \"$dir\\patch\" -Force -Recurse"
    ],
    "bin": "FileLocatorPro.exe",
    "shortcuts": [
        [
            "FileLocatorPro.exe",
            "FileLocator Pro"
        ]
    ],
    "persist": [
        "config\\config_v9.xml",
        "config\\history.xml",
        "config\\index.xml"
    ]
}

=== kkzzhizhou/scoop-apps/bucket/pencil.json
{
    "version": "4.0.0",
    "description": "GUI prototyping tool",
    "homepage": "https://pencil.evolus.vn",
    "license": "GPL-2.0-only",
    "url": "https://pencil.evolus.vn/dl/V4.0.0.ga/Pencil-4.0.0.ga.exe#/dl.7z",
    "hash": "19dd56fbcdeecf66def18ec6766f4796127aedf2342798c48cde2e74bef498f0",
    "architecture": {
        "64bit": {
            "pre_install": "Expand-7zipArchive \"$dir\\`$PLUGINSDIR\\app-64.7z\" \"$dir\""
        },
        "32bit": {
            "pre_install": "Expand-7zipArchive \"$dir\\`$PLUGINSDIR\\app-32.7z\" \"$dir\""
        }
    },
    "post_install": "Remove-Item \"$dir\\`$*\" -Force -Recurse",
    "bin": "Pencil.exe",
    "shortcuts": [
        [
            "Pencil.exe",
            "Pencil"
        ]
    ],
    "checkver": {
        "github": "https://github.com/evolus/pencil"
    },
    "autoupdate": {
        "url": "https://pencil.evolus.vn/dl/V$version.ga/Pencil-$version.ga.exe#/dl.7z",
        "hash": {
            "url": "$baseurl/CHECKSUM"
        }
    }
}

=== kkzzhizhou/scoop-apps/bucket/uutils-diffutils.json
{
    "version": "0.6.0",
    "description": "A cross-platform Rust reimplementation of GNU diffutils (binaries compiled with MSVC), with some options or behaviors potentially differing from GNU diffutils.",
    "homepage": "https://uutils.github.io/diffutils/",
    "license": {
        "identifier": "MIT OR Apache-2.0",
        "url": "https://github.com/uutils/diffutils/blob/HEAD/LICENSE-MIT"
    },
    "suggest": {
        "vcredist": "extras/vcredist2022"
    },
    "architecture": {
        "64bit": {
            "url": "https://github.com/uutils/diffutils/releases/download/v0.6.0/diffutils-x86_64-pc-windows-msvc.zip",
            "hash": "69063ab317b737314ac509a1db0edee4be0b75892ac098969104103d9748e413"
        }
    },
    "bin": [
        "diffutils.exe",
        [
            "diffutils.exe",
            "cmp",
            "cmp"
        ],
        [
            "diffutils.exe",
            "diff",
            "diff"
        ],
        [
            "diffutils.exe",
            "diff3",
            "diff3"
        ],
        [
            "diffutils.exe",
            "sdiff",
            "sdiff"
        ]
    ],
    "checkver": {
        "github": "https://github.com/uutils/diffutils"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/uutils/diffutils/releases/download/v$version/diffutils-x86_64-pc-windows-msvc.zip"
            }
        }
    }
}

=== kkzzhizhou/scoop-apps/bucket/flog.json
{
    "description": " A fake log generator for common log formats such as apache-common, apache error and RFC3164 syslog.",
    "homepage": "https://github.com/mingrammer/flog",
    "version": "0.3.2",
    "license": "MIT",
    "architecture": {
        "64bit": {
            "url": "https://github.com/mingrammer/flog/releases/download/v0.3.2/flog_0.3.2_windows_amd64.tar.gz",
            "hash": "a7a1d35623df3754dffbd0de9e4c5b46d25721fbd5d7eca16ab5a4eaf510f8e1"
        }
    },
    "bin": "flog.exe",
    "checkver": "github",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/mingrammer/flog/releases/download/v$version/flog_$version_windows_amd64.tar.gz",
                "hash": {
                    "url": "$baseurl/flog_$version_checksums.txt"
                }
            }
        }
    }
}
